// <auto-generated />
using System;
using DataAccessLayer.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(FleetContext))]
    [Migration("20220514200330_AddressBug")]
    partial class AddressBug
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccessLayer.Model.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Zipcode")
                        .HasColumnType("int");

                    b.HasKey("AddressID");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("DataAccessLayer.Model.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandID"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("BrandID");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("DataAccessLayer.Model.Driver", b =>
                {
                    b.Property<int>("DriverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverID"), 1L, 1);

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("FuelCardID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NationalInsuranceNr")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("VehicleID")
                        .HasColumnType("int");

                    b.HasKey("DriverID");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("DataAccessLayer.Model.DriverDriverLicenseType", b =>
                {
                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<int>("DriverLicenseTypeID")
                        .HasColumnType("int");

                    b.HasKey("DriverID", "DriverLicenseTypeID");

                    b.HasIndex("DriverLicenseTypeID");

                    b.ToTable("DriverDriverLicenseType");
                });

            modelBuilder.Entity("DataAccessLayer.Model.DriverLicenseType", b =>
                {
                    b.Property<int>("DriverLicenseTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverLicenseTypeID"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("DriverLicenseTypeID");

                    b.ToTable("DriverLicenseType");
                });

            modelBuilder.Entity("DataAccessLayer.Model.FuelCard", b =>
                {
                    b.Property<int>("FuelCardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuelCardID"), 1L, 1);

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("DriverID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Pincode")
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("FuelCardID");

                    b.HasIndex("DriverID")
                        .IsUnique()
                        .HasFilter("[DriverID] IS NOT NULL");

                    b.ToTable("FuelCard");
                });

            modelBuilder.Entity("DataAccessLayer.Model.FuelCardFuelType", b =>
                {
                    b.Property<int>("FuelCardID")
                        .HasColumnType("int");

                    b.Property<int>("FuelTypeID")
                        .HasColumnType("int");

                    b.HasKey("FuelCardID", "FuelTypeID");

                    b.HasIndex("FuelTypeID");

                    b.ToTable("FuelCardFuelType");
                });

            modelBuilder.Entity("DataAccessLayer.Model.FuelType", b =>
                {
                    b.Property<int>("FuelTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuelTypeID"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("FuelTypeID");

                    b.ToTable("FuelType");
                });

            modelBuilder.Entity("DataAccessLayer.Model.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"), 1L, 1);

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DataAccessLayer.Model.Vehicle", b =>
                {
                    b.Property<int>("VehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleID"), 1L, 1);

                    b.Property<int?>("AmountDoors")
                        .HasColumnType("int");

                    b.Property<int>("BrandID")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("DriverID")
                        .HasColumnType("int");

                    b.Property<int>("FuelTypeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("VehicleTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("VehicleID");

                    b.HasIndex("BrandID");

                    b.HasIndex("DriverID")
                        .IsUnique()
                        .HasFilter("[DriverID] IS NOT NULL");

                    b.HasIndex("FuelTypeID");

                    b.HasIndex("VehicleTypeID");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("DataAccessLayer.Model.VehicleType", b =>
                {
                    b.Property<int>("VehicleTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleTypeID"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("VehicleTypeID");

                    b.ToTable("VehicleType");
                });

            modelBuilder.Entity("DataAccessLayer.Model.Address", b =>
                {
                    b.HasOne("DataAccessLayer.Model.Driver", "Driver")
                        .WithOne("Address")
                        .HasForeignKey("DataAccessLayer.Model.Address", "AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("DataAccessLayer.Model.DriverDriverLicenseType", b =>
                {
                    b.HasOne("DataAccessLayer.Model.Driver", "Driver")
                        .WithMany("DriverDriverLicenseType")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Model.DriverLicenseType", "DriverLicenseType")
                        .WithMany("DriverDriverLicenseType")
                        .HasForeignKey("DriverLicenseTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("DriverLicenseType");
                });

            modelBuilder.Entity("DataAccessLayer.Model.FuelCard", b =>
                {
                    b.HasOne("DataAccessLayer.Model.Driver", "Driver")
                        .WithOne("FuelCard")
                        .HasForeignKey("DataAccessLayer.Model.FuelCard", "DriverID");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("DataAccessLayer.Model.FuelCardFuelType", b =>
                {
                    b.HasOne("DataAccessLayer.Model.FuelCard", "FuelCard")
                        .WithMany("FuelCardFuelType")
                        .HasForeignKey("FuelCardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Model.FuelType", "FuelType")
                        .WithMany("FuelCardFuelType")
                        .HasForeignKey("FuelTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuelCard");

                    b.Navigation("FuelType");
                });

            modelBuilder.Entity("DataAccessLayer.Model.Vehicle", b =>
                {
                    b.HasOne("DataAccessLayer.Model.Brand", "Brand")
                        .WithMany("Vehicle")
                        .HasForeignKey("BrandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Model.Driver", "Driver")
                        .WithOne("Vehicle")
                        .HasForeignKey("DataAccessLayer.Model.Vehicle", "DriverID");

                    b.HasOne("DataAccessLayer.Model.FuelType", "FuelType")
                        .WithMany("Vehicle")
                        .HasForeignKey("FuelTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Model.VehicleType", "VehicleType")
                        .WithMany("Vehicle")
                        .HasForeignKey("VehicleTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Driver");

                    b.Navigation("FuelType");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("DataAccessLayer.Model.Brand", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DataAccessLayer.Model.Driver", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("DriverDriverLicenseType");

                    b.Navigation("FuelCard");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DataAccessLayer.Model.DriverLicenseType", b =>
                {
                    b.Navigation("DriverDriverLicenseType");
                });

            modelBuilder.Entity("DataAccessLayer.Model.FuelCard", b =>
                {
                    b.Navigation("FuelCardFuelType");
                });

            modelBuilder.Entity("DataAccessLayer.Model.FuelType", b =>
                {
                    b.Navigation("FuelCardFuelType");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DataAccessLayer.Model.VehicleType", b =>
                {
                    b.Navigation("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
